const _ = require('lodash')

module.exports = {
  all: [
    {
      id: 1,
      username: 'admin',
      password: 'password',
      name: 'Jett Liu',
      resources: [
        'RIGHT_GLOBAL_SEARCH',
        'RIGHT_VIEW_EDIT_SCREEN',
        'RIGHT_VIEW_HTML_APP',
        'RIGHT_VIEW_UTILITIES',
        'RIGHT_VIEW_WK_QUEUE',
        'RIGHT_MAINTAIN_FFM_CREDENTIAL',
        'RIGHT_MANAGE_IFP_CALL_VOLUME',
        'RIGHT_EDIT_ROLE_Carrier Sync Standard',
        'RIGHT_EDIT_ROLE_XM Developer',
        'RIGHT_CAN_SUBMIT_TEXT_OPT_IN',
        'RIGHT_VIEW_PRINT_SG_PDF',
        'RIGHT_EDIT_ROLE_Extranet - Lead Seller',
        'RIGHT_VIEW_MEDICARE_SALES_LICENSING',
        'RIGHT_SAVE_LETTER_TEMPLATE',
        'RIGHT_CROSS_SELL_ATTEMPT',
        'RIGHT_CROSS_SELL_COMMITMENT',
        'RIGHT_EDIT_ROLE_Extranet - Lead Buyer',
        'RIGHT_CARRIER_ADMINISTRATION',
        'RIGHT_EDIT_ROLE_Email Admin',
        'RIGHT_EDIT_ROLE_Extranet - Carrier Bidder',
        'RIGHT_EDIT_ROLE_Extranet - EOD Read Only',
        'RIGHT_EDIT_ROLE_Extranet - EOD with XML',
        'RIGHT_EDIT_ROLE_Finance',
        'RIGHT_EDIT_ROLE_Outbound Rep',
        'WEBCONSOLE.BASIC',
        'RIGHT_LEAD_GLOBAL_SEARCH',
        'RIGHT_START_TPI_APPLICATION',
        'RIGHT_UPLOAD_DOCUMENT',
        'RIGHT_VIEW_AUTO_EMAIL_LEADS',
        'RIGHT_VIEW_EXCEPTIONS',
        'RIGHT_VIEW_HYPERLINK_APPLICATION_STATUS',
        'RIGHT_VIEW_IFP_DOC_MANAGER',
        'RIGHT_VIEW_OUTGOING_TEMPLATE',
        'RIGHT_VIEW_SEARCH',
        'RIGHT_VIEW_UNIV_WRK_QUEUE',
        'RIGHT_RESEND_APPLICATION',
        'RIGHT_TO_DRX_DATA_ENTRY',
        'RIGHT_TRIGGER_UHC_ACE',
        'RIGHT_CAN_SUBMIT_TCPAS',
        'RIGHT_EDIT_ROLE_Carrier Administrator',
        'RIGHT_TODAY_OPPORTUNITY',
        'RIGHT_EDIT_ROLE_Carrier Sync Admin',
        'RIGHT_SMBO_PILOT_TESTING',
        'RIGHT_VIEW_MEDICARE_MANAGER_OVERRIDE_CODE_ADMIN',
        'RIGHT_EDIT_ROLE_Medicare Sales',
        'RIGHT_SAVE_DOC_SERVICE_TICKET',
        'RIGHT_EDIT_ROLE_Medicare Developer',
        'RIGHT_SALES_PROGRAMS',
        'RIGHT_VIEW_MEDICARE_INBOUND_SCRIPT',
        'RIGHT_EDIT_ROLE_Finance - Rider Admin',
        'RIGHT_VIEW_MEDICARE_OUTBOUND_SCRIPT',
        'RIGHT_EDIT_ROLE_External Supervisor',
        'RIGHT_ADD_MEMBERS',
        'RIGHT_EDIT_ROLE_Auction Access (CR)',
        'RIGHT_EDIT_ROLE_Auction Access (Finance)',
        'RIGHT_EDIT_ROLE_Clerk',
        'RIGHT_EDIT_ROLE_Extranet - EPI',
        'RIGHT_EDIT_ROLE_sbg-Sales Rep',
        'RIGHT_GENERAL_AGENT_MAINTEN',
        'RIGHT_IFP_ADD_RIDERS',
        'RIGHT_VIEW_MEDICARE_APPOINTMENT_SUMMARY',
        'RIGHT_VIEW_KEY_INFO',
        'RIGHT_VIEW_LEAD_SEARCH',
        'RIGHT_VIEW_SALES_REP_ASSIGN',
        'RIGHT_SENT_PASSWORD_RESET_EMAIL',
        'RIGHT_LIVE_OPS_MAPPING',
        'RIGHT_EDIT_ROLE_sbg-Retention Account Manager',
        'RIGHT_SMB_AGENT_DASHBOARD',
        'RIGHT_VIEW_KEYINFO_APPOINTMENTS',
        'RIGHT_AGENT_CONTROLLER_EDIT',
        'RIGHT_WC_REPORTING',
        'RIGHT_CREATE_SUBMITTED_APP_BATCH',
        'RIGHT_EDIT_ROLE_Customer Service',
        'RIGHT_EDIT_ROLE_Extranet - Benefit Administrator',
        'RIGHT_EDIT_ROLE_Reviewer',
        'RIGHT_VIEW_SGDOCMANAGER',
        'RIGHT_WRK_QUEUE_CREATION',
        'RIGHT_SAVE_PLAN_PROFILE',
        'RIGHT_VIEW_CREATE_NEW_LEAD',
        'RIGHT_MANAGE_IFP_CHAT_VOLUME',
        'RIGHT_SG_RTC_SCHEDULE',
        'RIGHT_EDIT_ROLE_MS Enrollment Specialist',
        'RIGHT_EDIT_AS',
        'RIGHT_TRANSCRIBE_SUBSIDY_DATA',
        'RIGHT_VIEW_SALES_LICENSING',
        'RIGHT_RESEND_T2S_TEXT_EMAIL',
        'RIGHT_SBG_TIER_RULE_MAINTENANCE',
        'RIGHT_VIEW_SUBSIDY_DATA',
        'RIGHT_AUTO_LOGIN_AGENT_PORTAL',
        'RIGHT_ADD_EMPLOYEES',
        'RIGHT_EDIT_MEMBERS',
        'RIGHT_EDIT_ROLE_Auction Access (Legal)',
        'RIGHT_EDIT_ROLE_External User',
        'RIGHT_EDIT_ROLE_Forms Administrator',
        'RIGHT_EDIT_ROLE_Partner Approver',
        'RIGHT_EDIT_ROLE_Supervisor',
        'RIGHT_EDIT_TRACKING_DATES',
        'RIGHT_VIEW_BATCH_ENTRY',
        'RIGHT_VIEW_COMPANY_INFO',
        'RIGHT_VIEW_SERVICE_TICKET',
        'RIGHT_WORK_SKIPPED_BATCH',
        'RIGHT_AGENT_MANAGEMENT_CONSOLE',
        'RIGHT_EDIT_ROLE_sbg-External User',
        'USER.UPDATE_USER_FOR_BO',
        'RIGHT_EDIT_ROLE_Subsidy Entry Clerk',
        'RIGHT_EDIT_ROLE_sbg-Enrollment User',
        'RIGHT_EDIT_ROLE_Carrier Sync Read-Only',
        'RIGHT_EDIT_ROLE_sbg-NB Account Manager',
        'RIGHT_EDIT_MEDICARE_CARRIER_PLAN',
        'RIGHT_DELETE_LETTER_TEMPLATE',
        'RIGHT_EDIT_ROLE_Medicare Customer Service',
        'RIGHT_VIEW_SCRIPT_ERROR_REPORTING',
        'RIGHT_ADMIN_CALENDAR',
        'RIGHT_SAVE_COM_LOG',
        'RIGHT_CREATE_APPLICATION_WITH_PLAN',
        'RIGHT_EDIT_ROLE_Auction Access (PM)',
        'RIGHT_EDIT_ROLE_EOD Administrator',
        'RIGHT_EDIT_ROLE_Extranet - EPI with XML',
        'RIGHT_EDIT_ROLE_Telesales Rep',
        'RIGHT_RECEIVE_EMAIL_WQ_FOR_SALES',
        'RIGHT_VIEW_AUTO_EMAIL',
        'RIGHT_VIEW_COMP_CREDIT_ASSIGN',
        'RIGHT_VIEW_EMPLOYEES',
        'RIGHT_VIEW_EXPANDED_REVENUE_IMPACT_DATE',
        'RIGHT_VIEW_SUBMITTED_APP_MANAGER',
        'RIGHT_REAL_TIME_CALLING_DASHBOARD',
        'RIGHT_EDIT_ROLE_EOD Email Approver',
        'RIGHT_EDIT_ROLE_Workforce Manager',
        'RIGHT_SALES_PERFORMANCE',
        'RIGHT_LEAD_MONETIZATION',
        'RIGHT_VIEW_ORGANIZATION_CONFIGURATION',
        'RIGHT_SEND_PROPOSAL_EMAIL',
        'RIGHT_ADD_OFFLINE_CARRIER',
        'RIGHT_ATTACHMENT_MANAGER',
        'RIGHT_EDIT_POLICIES',
        'RIGHT_EDIT_REVENUE_COUNTS',
        'RIGHT_EDIT_ROLE_Auction Administrator',
        'RIGHT_EDIT_ROLE_Extranet - EOD',
        'RIGHT_EDIT_ROLE_Extranet - EOD Administrator',
        'RIGHT_EDIT_ROLE_Extranet - Prescreen',
        'RIGHT_EDIT_ROLE_Inquiry Only',
        'RIGHT_EDIT_ROLE_Reviewer-CS',
        'RIGHT_EDIT_ROLE_Standard Developer',
        'RIGHT_SBG_ADD_RIDERS',
        'RIGHT_EDIT_LATE_PAYMENT',
        'RIGHT_VIEW_SEND_BULK_EMAIL',
        'RIGHT_VIEW_UPDATE_USERS',
        'RIGHT_CAN_NOTIFY_CUSTOMER',
        'RIGHT_MEDICARE_ENROLLMENT_DASHBOARD',
        'RIGHT_CALL_CISCO_CAD',
        'RIGHT_ACE_MISSION_CONSOLE',
        'RIGHT_Agent_Call',
        'RIGHT_SEND_PPE_CROSS_SELL',
        'RIGHT_EDIT_DOCUMENT_CONTENT',
        'RIGHT_EDIT_ROLE_Customer Retention',
        'RIGHT_EDIT_ROLE_sbg-Finance-XM',
        'RIGHT_MEDICARE_CALL_VOLUME',
        'RIGHT_SCRIPT_MESSAGE',
        'RIGHT_EDIT_ROLE_Extranet - Quoting Service',
        'RIGHT_EDIT_ROLE_Medicare Supervisor',
        'RIGHT_EDIT_BENEFIT_ADMIN_TEXT',
        'RIGHT_EDIT_ROLE_Auction Access (AS)',
        'RIGHT_EDIT_ROLE_Benefit Summary Admin',
        'RIGHT_EDIT_ROLE_EOD Sales Support',
        'RIGHT_EDIT_ROLE_Extranet - EOD Agent Admin',
        'RIGHT_EDIT_ROLE_Partner Manager',
        'RIGHT_EDIT_ROLE_ifp-Sales Rep',
        'RIGHT_GEN_OUTGOING_CORR',
        'RIGHT_VIEW_ACCOUNT_MNGER_ASSIGN',
        'RIGHT_VIEW_BENEFIT_SUMMARY',
        'RIGHT_VIEW_BULK_EMAIL',
        'RIGHT_VIEW_IFP_DOC_SCREEN',
        'RIGHT_VIEW_OPS_SRCH_ASSIGN',
        'RIGHT_EDIT_ROLE_EOD Sales Supervisor',
        'RIGHT_EDIT_ROLE_Medicare Compliance',
        'RIGHT_EDIT_ROLE_Senior Enrollment Rep',
        'RIGHT_VIEW_PRINT_IFP_PDF',
        'RIGHT_OFFLINE_CARRIER_PLAN',
        'RIGHT_OFFLINE_CARRIER_CREATE_APP',
        'RIGHT_IFP_ADMIN_RIDERS',
        'RIGHT_EDIT_ROLE_Medicare Enrollment',
        'RIGHT_EDIT_ROLE_Finance - XM',
        'RIGHT_EDIT_ROLE_Email Approver',
        'RIGHT_SAVE_SERVICE_TICKET',
        'RIGHT_AGENT_CONTROLLER',
        'RIGHT_EDIT_ROLE_Admin Developer',
        'RIGHT_EDIT_ROLE_Sales Support',
        'RIGHT_EDIT_ROLE_sbg-Account Manager',
      ],
    },
    {
      id: 2,
      username: 'user1',
      password: 'password',
      name: 'Bing Hu',
      resources: ['RIGHT_GLOBAL_SEARCH', 'RIGHT_VIEW_SEARCH'],
    },
  ].map((user) => {
    return {
      ...user,
      token: `valid-token-for-${user.username}`,
    }
  }),
  authenticate({ username, password }) {
    return new Promise((resolve, reject) => {
      const matchedUser = this.all.find(
        (user) => user.username === username && user.password === password
      )
      if (matchedUser) {
        resolve(this.json(matchedUser))
      } else {
        reject(new Error('Invalid user credentials.'))
      }
    })
  },
  findBy(propertyName, value) {
    const matchedUser = this.all.find((user) => user[propertyName] === value)
    return this.json(matchedUser)
  },
  json(user) {
    return user && _.omit(user, ['password'])
  },
}
